name: Deploy app manifests
run-name: Deploy app manifests

on:
  push:
    branches:
      - main
    # paths:
      # - cdn/kis-fe/deploy_setup.json

# Nastavime, aby nikdy nebezelo vic instanci workflow najednou. Tim je zajisteno,
# ze toto workflow naposledy pobezi vzdy na poslednim commitu v masteru.
concurrency:
  group: deploy-app-manifests

jobs:
  get-changed-envs:
    runs-on: ubuntu-latest
    name: Generate manifest to modified environments
    outputs:
      matrix: ${{ steps.changes.outputs.matrix }}
      has_changes: ${{ steps.changes.outputs.has_changes }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get Changed Envs
        id: changes
        run: |
          ENVS=("deva" "int" "prs" "pred" "prod")
          CHANGED_ENVS=()

          OLD_SETUP_FILE=$(git show HEAD~1:cdn/kis-fe/deploy_setup.json)
          NEW_SETUP_FILE=$(git show HEAD:cdn/kis-fe/deploy_setup.json)

          for ENV in "${ENVS[@]}"; do
            if diff <(echo "$OLD_SETUP_FILE" | jq -S ".$ENV") <(echo "$NEW_SETUP_FILE" | jq -S ".$ENV") > /dev/null; then
              echo "No changes detected for $ENV"
            else
              echo "Changes detected for $ENV"
              VERSION="$(jq -S '.$ENV.targetRevision' "$NEW_SETUP_FILE")"
              URL="$(jq -S '.$ENV.repoURL' "$NEW_SETUP_FILE")"
              CHANGED_ENVS+=("\"$ENV:$VERSION:$URL\"")
            fi
          done

          # changed envs
          echo "changed ENVS: ${CHANGED_ENVS[*]}"

          if [[ ${#CHANGED_ENVS[@]} -eq 0 ]]; then
            HAS_CHANGES="has_changes=false"
            MATRIX="matrix={\"envs\":[]}"
          else
            HAS_CHANGES="has_changes=true"
            MATRIX="matrix={\"envs\":[$(IFS=,; echo "${CHANGED_ENVS[*]}")]}"
          fi

          # matrix
          echo "::debug final matrix: $MATRIX"

          # Output JSON matrix and HAS_CHANGES for GitHub Actions
          echo "$HAS_CHANGES" >> $GITHUB_OUTPUT
          echo "$MATRIX" >> $GITHUB_OUTPUT

  generate-manifest-per-env:
    runs-on: ubuntu-latest
    name: Create PR to changed ENV
    needs: get-changed-envs
    if: ${{ needs.get-changed-envs.outputs.has_changes == 'true' }}
    strategy:
      matrix: ${{ fromJSON(needs.get-changed-envs.outputs.matrix) }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: test
        run: echo "ENV?? ${{matrix.envs}}"  
    # uses: ./.github/workflows/update_env_branch.yml
    # with: 
    #   environment: ${{ matrix.envs }}


        
          
