name: Deploy app manifests
run-name: Deploy app manifests

on:
  push:
    branches:
      - main
    paths:
      - cdn/kis-fe/deploy_setup.yml

# Nastavime, aby nikdy nebezelo vic instanci workflow najednou. Tim je zajisteno,
# ze toto workflow naposledy pobezi vzdy na poslednim commitu v masteru.
concurrency:
  group: deploy-app-manifests

jobs:
  generate-manifest-per-env:
    runs-on: ubuntu-latest
    name: Generate manifest to modified environments
    defaults:
      run:
        working-directory: ./.github/scripts
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make the script file executable
        run: chmod +x get_changed_envs.sh  

      - name: Get Changed Envs
        id: changes
        run: |
          ./get_changed_envs.sh
